name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Resolve lockfile hash
        id: lockfile-hash
        run: echo "::set-output name=hash::${{ hashFiles('yarn.lock') }}"

      - name: Caching
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-yarn-${{ steps.lockfile-hash.outputs.hash }}

      - name: Install deps if not cached
        if: steps.cache-deps.outputs.cache-hit == ''
        run: yarn install

      - name: Rewrite titles
        run: yarn rewrite-title

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist
